#version 430 core
layout(local_size_x = 64) in;

layout(std430, binding = 0) readonly buffer TransformBuf {
    vec4 xzyr[]; // x=x, y=z, z=y, w=rotY
};

layout(std430, binding = 6) writeonly buffer ShadowVisBuf {
    uint shadow_visible[];
};

layout(std430, binding = 7) buffer ShadowIndBuf {
    uint indexCount;
    uint instanceCount;
    uint firstIndex;
    uint baseVertex;
    uint baseInstance;
};

uniform vec3  camPos;
uniform float maxDistSq;
uniform int   total_count;

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (int(idx) >= total_count) return;
    vec4 data = xzyr[idx];
    float dx = data.x - camPos.x;
    float dz = data.y - camPos.z;
    if (dx * dx + dz * dz <= maxDistSq) {
        uint slot = atomicAdd(instanceCount, 1u);
        shadow_visible[slot] = idx;
    }
}
